name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: snok/install-poetry@v1
    - run: poetry install
    - run: |
        poetry run black --check .
        poetry run isort --check .
        poetry run flake8 .
    - run: pytest --cov=. --cov-report=xml
    - uses: codecov/codecov-action@v2
